services:
  - type: web
    name: laravel-inertia-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: RUN_MIGRATIONS
        value: false
